#pragma once

#include "core/Target.h"

#include "../GameStructs/PolyphonyGL.h"

extern void (*pglPopMatrix)();
extern void (*pglLoadIdentity)();
extern void (*pglEnable)(pglFlags);
extern void (*pglDisable)(pglFlags);
extern void (*pglAccum)(int, float);
extern void (*pglAccumBuffer)(unsigned int, char, int, int);
extern void (*pglAllocatePacket)(unsigned int);
extern void (*pglAlphaFail)(unsigned int);
extern void (*pglAlphaFunc1ub)(char val, unsigned char val2);
extern void (*pgluTriangleStrip3fv)(int, MathVector3*, MathVector3*, MathVector3*, int*);
extern void (*pglColor)(unsigned int);
extern void (*pglWcRect2i)(int, int, int, int);
extern void (*pglColor4f)(float, float, float, float);
extern void (*pglColor4ftoi)(float, float, float, float);
extern void (*pglGetViewport)(float*, float*, float*, float*);
extern void (*pglScale)(float, float, float);
extern void (*pglAppendGIFPacket)(unsigned long long);
extern void (*pglAppendImagePacket)(unsigned long long);
extern void (*pglApplyMatrix)(float*, float*);
extern void (*pglBeginStrip)();
extern void (*pglBlendFunc1ub)();
extern void (*pglClear)();
extern void (*pglClearColor)(float, float, float, float);
extern void (*pglClearColor1ui)(unsigned int);
extern void (*pglClearDepth)(float);
extern void (*pglClutBuffer)(int, unsigned long long);
extern void (*pglClutLoad)(int);
extern void (*pglClutOffset)(char);
extern void (*pglColorBuffer)(unsigned int tbp, char tbw, int a3, int a4);
extern void (*pglColorMask1ui)(unsigned int color);
extern void (*pglCounterMatrix)(float* matrix);
extern void (*pglCullFace)(int mode);
extern void (*pglCylinderMapAxis)(float, float, float, float, float, float);
extern void (*pglCylinderMapHint)(float, float, float);
extern void (*pglCylinderMapT)(float, float);
extern void (*pglDMABuffer)(int, int);
extern void (*pglDepthBias)(float);
extern void (*pglDepthBuffer)(unsigned int a1, unsigned int a2);
extern void (*pglDepthMask)(char a1);
extern void (*pglDestinationAlphaFunc)(int gsTestValue);
extern void (*pglDisplayMask)(char enableDisplayMask);
extern void (*pglDisplayMode)(int a1, int outputMode, int a3);
extern void (*pglDisplayResolution)(short width, short height);
extern void (*pglDisplayViewport)(short x, short y, short width, short height);
extern void (*pglDitherMatrix)(int*);
extern void (*pglEndStrip)();
extern void (*pglExit)();
extern void (*pglFinish)();
extern void (*pglFlush)();
extern void (*pglFlushCache)();
extern void (*pglFog)(float, float);
extern void (*pglFogColor)(float r, float g, float b);
extern void (*pglFogColor1ui)(int fogcol, unsigned int color);
extern void (*pglFrontFace)(int a1);
extern void (*pglFree)(int a1);
extern int (*pglGetColor1ui)();
extern void (*pglGetColorBuffer)(int*, int*, int*, int*);
extern int (*pglGetCullFace)();
extern int (*pglGetField)(int);
extern unsigned int (*pglGetFogColor1ui)(int);
extern int (*pglGetWorkPage)();
extern void (*pglInit)();
extern void (*pglInverse_0)(float* matrix);
extern char (*pglIsInFrame)();
extern void (*pglLightModelfv)(int sides, float*);
extern void (*pglLightfv)(int unkMode, int a2, int a3);
extern void (*pglLoadIdentity)();
extern void (*pglLoadIdentityTranslate)(float* matrix);
extern void (*pglLoadMatrix)();
extern void (*pglLock)();
extern void (*pglMatrixMode)(int mode);
extern void (*pglMultMatrix)(float* matrix);
extern void (*pglMultMatrixLeft)(float* matrix);
extern void (*pglNewFrame)();
extern void (*pglObjectScale)(float a1, float a2, float a3);
extern void (*pglOrtho)(float, float, float, float, float, float);
extern void (*pglPixelCenter)(float a1, float a2);
extern void (*pglPixelDomain)(float a1, float a2, float a3);
extern void (*pglPoolMode)(int mode);
extern void (*pglPopAttrib)();
extern void (*pglPopMatrix)();
extern void (*pglPushAttrib)(int attrib);
extern void (*pglPushMatrix)();
extern void (*pglResetCache)();
extern void (*pglRotate)(float x, float y, float z, float w);
extern void (*pglRotateX)(float x);
extern void (*pglRotateY)(float y);
extern void (*pglRotateZ)(float z);
extern void (*pglSaveSkinningMatrix)(int a1, int a2);
extern void (*pglScale)(float x, float y, float z);
extern void (*pglScanMask)(int scanMskOp);
extern void (*pglScissor)(int x, int y, int w, int h);
extern void (*pglSetTexCoords)(int a1, int texCoords, int count);
extern void (*pglSignalSema)(int dmaChannel);
extern void (*pglStoreMatrix)(float* matrix);
extern void (*pglStrip)(int num, float* vertices, float* texcoords, float* normals, int* a5, int* a6);
extern void (*pglSyncDMA)();
extern void (*pglSyncV)(int a1);
extern void (*pglTaggedAllocate)(int a1, int a2);
extern void (*pglTexFlush)();
extern void (*pglTexGenf)(int unkMode, float value);
extern void (*pglTexImage)(void* pgluTex, int mipmapLevel, unsigned int actualOffset, char a4, int tbwActual);
extern void (*pglTexParameter)(void* pgluTex, pgluParamType paramType, short value);
extern void (*pglTexRegion)(void* pgluTex, int a2, short x, short y);
extern void (*pglTranslate)(float x, float y, float z);
extern void (*pglTriangleStrip)(void* dmaThing, float* vertices, float* unused, unsigned int* colors,
    float* texcoordUV, int numVertex, char useTrifanInsteadOfStrip);
extern void (*pglTriangleStrip_0)(float* vertices, float* unused, unsigned int* colors, float* texcoordUV, int numVertex);
extern void (*pglUnkEnableSomething)();
extern void (*pglUnlock)();
extern void (*pglVariableColorOffset)(float r, float g, float b, float a);
extern void (*pglVariableColorScale)(float r, float g, float b, float a);
extern void (*pglViewport)(float x, float y, float w, float h);
extern void (*pglWaitSema)(int dmaChannel);
extern void (*pglWcLine2i)(int x1, int y1, int x2, int y2);
extern void (*pglWcRect2i)(int x, int y, int w, int h);
extern void (*pglWcSliceRect2i)(int x, int y, int w, int h);
extern void (*pglWcSliceSprite2f)(int x, int y, float a3, float a4, int a5, float a6, int a7, float a8);
extern void (*pglWcSprite2f)(float a1, float a2, float a3, int a4, float a5, int a6, float a7);
extern void (*pglWritePixelsImm)(unsigned int a1, int a2, int a3, int a4, int a5, int a6, int a7);
extern void (*pglWritePixelsPath1)(unsigned int a1, int a2, int a3, int a4, int a5, int width, int height, int* a8);
extern void (*pglWritePixelsPath3)(unsigned int a1, int format, int unkType, int a4, int a5, int width, int height, int* a8);
extern void (*pgl_SetGSControlRegister)(short a1, short a2, short a3, short a4);
extern void (*pglmRandomSeed)(float val);
extern void (*pgluApplyClutAnimation)(void*);
extern void (*pgluApplyClutPatch)(void* pgluTexSet, void* clutPatch);
extern int (*pgluCacheGetSize)(int texSize, void* pgluTexSet);
extern void (*pgluCacheTexSetPath3)(void* pgluTexSet);
extern void (*pgluCallShape)(void* pgluShape);
extern void (*pgluCallTstrip)(int a1, int a2, float a3, float a4, float a5, float a6);
extern int (*pgluComputeTexSize)(int format, int w, int h, int* outUnk);
extern void (*pgluCopyPixelsToAlpha)(unsigned int a1, unsigned int a2, unsigned int a3, int a4, int a5);
extern void (*pgluCustomizeShimmer)(int a1, float a2, float a3, float a4, float a5, float a6);
extern void (*pgluDepthOffset)(float value);
extern void (*pgluExternalMatIndex)(int idx);
extern void (*pgluExternalTexIndex)(int idx);
extern void (*pgluField)(int field);
extern void (*pgluFontFacePDI)(/* 11 arguments.. */);
extern void (*pgluGammaCorrection)(int a1, float a2);
extern void (*pgluInitShimmer)(unsigned int a1, int a2, int a3);
extern void (*pgluJitter)(int a1, int a2);
extern void (*pgluLoadIdentityClut)(int a1);
extern void (*pgluMapShape)(void* pgluShape);
extern void (*pgluMapTexSet)(void* pgluTexSet);
extern void (*pgluMatTable)(int tableIdx);
extern void (*pgluMaterialFunc)(int packedBits);
extern float (*pgluRandomFloat_Guessed)();
extern void (*pgluRandomize)(int value);
extern void (*pgluReflection)(float a1, float a2, float a3, float a4, float a5, float a6);
extern void (*pgluRelocateTexSet)(void* pgluTexSet, unsigned int baseFrameBufferPos);
extern void (*pgluResetClutAnimation_0)(void* a1, int a2);
extern void (*pgluSetVertColors)(void* dmaThing, unsigned int* colors, int numColors);
extern void (*pgluSetupFontFacePDI)(void*);
extern void (*pgluSetupKanjiImagePDI)(int offset, int format, int a3, int a4, int a5, int width, int height);
extern void (*pgluShapeCallback)(void* callback);
extern void (*pgluShapeTweenRatio)(float tweenRatio);
extern void (*pgluShimmer)(void* unkMatrixMaybe);
extern void (*pgluShimmerMove)(void* unk);
extern void (*pgluSignalClutAnimation)(void* unk, int a2);
extern void (*pgluTexImage)(int mipLevel, unsigned int offset, char format, int a4);
extern char (*pgluTexIsCachedMaybe)(void*);
extern void (*pgluTexParameter)(pgluParamType param, int value);
extern void (*pgluTexRegion_SetClampSettings)(int unkMode, short x, short y);
extern void (*pgluTexReset)(void* pgluTex);
extern void (*pgluTexSize)(void* pgluTex, short width, short height);
extern void (*pgluTexSize_setTW_TH)(int tw, int th);
extern void (*pgluTexTable)(void* pgluTex);
extern void (*pgluTexture)(void* pgluTex);
extern void (*pgluTriangleList2fv)(int numVerts, void* a2, void* a3, void* a4);
extern void (*pgluTriangleStrip2fv)(int numVerts, float* vertices, int* a3, int* a4);
extern void (*pgluUpdateClutAnimation)(void*, void*, float);
extern void (*pgluWriteKanjiImagePDI)(void* a1);
